---
- hosts: [proxmox]
  become: true

- tasks:
  - name: deploiement debian ansible
    proxmox:
    vmid: 100
    node: uk-mc02
    api_user: root@pam
    api_password: 1q2w3e
    api_host: node1
    password: 123456
    hostname: example.org
    ostemplate: 'local:debian-11-turnkey-ansible_17.1-1_amd64.tar.gz'
...
